### PR TITLE
completed the code that produces a weather report from a json file

### PR DESCRIPTION
**Pull request by dyga01**
completed the code that produces a weather report from a json file

### CODE REVIEW

**Review by dluman — CHANGES_REQUESTED** [review]
We need to continue to use the API for this; I'll make more fields available through the climate endpoint so that we don't have to rely on the GitHub repository anymore. There'll also be a `news` module eventually, but that isn't reflected in this work.

So, the new API will subsume/supercede current `TNN` functionality.

**Comment by dluman** [comment]
> We need to continue to use the API for this; I'll make more fields available through the climate endpoint so that we don't have to rely on the GitHub repository anymore. There'll also be a `news` module eventually, but that isn't reflected in this work.
> 
> So, the new API will subsume/supercede current `TNN` functionality.

See #3, which restores the API schema under the new (and final, for now?) formula:
```
/v1/{name of service}
```
The above would translate to:
```
https://api.theterm.world/v1/climate
```

**Comment by dyga01** [comment]
I made some changes so the code uses the api_url to access the JSON data. However, there is still limited data i.e. {"wind": {"windy": false, "windspeed": 1.79}, "sun": false}. For our use case, should I also try and incorporate the port? Thanks for the feedback!

**Comment by dyga01** [comment]
I made some additional changes so that it can build local and virtual API calls. Please let me know what you think and if I should change anything. Thanks!

**Review by dluman — APPROVED** [review]
I made a few scale changes. The API automatically gives temperatures in `K` (for some reason). The scale defaults to `C` if `F` not specified.

**Pull request merged**
