### PR TITLE
Refactored to API structure to work like a plugin system

### PR DESCRIPTION
**Pull request by dluman**
Remade the API to allow us to slot in new modules as they become available. Would be nice to have a control structure that would allow us to "greenlight" or remove modules from the configuration should that be desirable. There's already a project file, but that's the domain of `pip`, et al.

No thoughts on an elegant solution, though.

### CODE REVIEW

**Review by dyga01 — DISMISSED** [review]
All of these changes look good to me.

**Comment by dluman** [comment]
Update: the API now points directly at OpenWeatherAPI and elaborates the API semantics. The name of the API precedes the noun, like so: `v1/climate/all` or `v1/climate/conditions` (each are the active endpoints for `climate`).

**Comment by dluman** [comment]
> Update: the API now points directly at OpenWeatherAPI and elaborates the API semantics. The name of the API precedes the noun, like so: `v1/climate/all` or `v1/climate/conditions` (each are the active endpoints for `climate`).

Note for future terminauts: this requires `ENV` variables for the OpenWeatherAPI key, and `lat`, `lon`. @dluman has them right now.

**Comment by dluman** [comment]
This one closed because I `merge`d the `narrator` branch. Neglected to think about that.

**Pull request merged**
